require('dotenv').config();
require('./database/init');
const express=require('express'), cors=require('cors'), bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken');
const {body, validationResult}=require('express-validator');
const db=require('./database/db');
const app=express(), PORT=process.env.PORT||5000, SECRET=process.env.JWT_SECRET||'development-only-secret';
app.use(cors()); app.use(express.json()); app.use(express.static('public'));
const fail=(res,status,message)=>res.status(status).json({success:false,message});
function auth(req,res,next){ const token=(req.headers.authorization||'').replace('Bearer ',''); try{req.user=jwt.verify(token,SECRET);next();}catch{return fail(res,401,'Please log in to continue.');} }
function fields(template){return {setup_cost:template.setup_cost,rent_deposit:template.rent_deposit,equipment_cost:template.equipment_cost,inventory_cost:template.inventory_cost,staff_cost:template.staff_cost,marketing_cost:template.marketing_cost,technology_cost:template.technology_cost,emergency_reserve:template.emergency_reserve,working_capital:template.working_capital};}
function recommend(capital, filters={}) { let rows=db.prepare('SELECT * FROM business_templates').all(); if(filters.category&&filters.category!=='Any') rows=rows.filter(r=>r.category===filters.category); if(filters.online==='Yes') rows=rows.filter(r=>r.online_supported); if(filters.physical==='Yes') rows=rows.filter(r=>r.physical_supported); return rows.map(t=>{const gap=t.recommended_capital-capital; let status= gap<=0 && capital>=t.recommended_capital*1.35 ? 'Large Reserve Available' : gap<=0 ? 'Within Estimated Budget' : capital>=t.minimum_capital*0.9 ? 'Near Budget — review lean allocation' : 'Requires Additional Capital'; const score=Math.max(0,100-Math.abs(gap)/Math.max(capital,1)*65)+(capital>=t.minimum_capital?15:0); return {...t,budget_status:status,fit_score:Math.round(score),capital_difference:gap,cost_breakdown:fields(t),why_fit: status==='Within Estimated Budget'?'Its recommended planning capital fits your entered amount.':status==='Large Reserve Available'?'Your amount supports the model and leaves room for a larger launch or reserve.':status==='Near Budget — review lean allocation'?'A lean version may be possible; validate costs and retain emergency cash.':'Its standard planning requirement is above your entered capital.'};}).sort((a,b)=>b.fit_score-a.fit_score); }
app.post('/api/auth/register',[body('name').trim().notEmpty(),body('email').isEmail(),body('password').isLength({min:8})],async(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Name, valid email and an 8-character password are required.');const {name,email,password}=req.body;if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return fail(res,409,'Email already registered.');const info=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email,bcrypt.hashSync(password,10));const user={id:info.lastInsertRowid,name,email,role:'owner'};res.status(201).json({success:true,user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})});});
app.post('/api/auth/login',async(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash))return fail(res,401,'Invalid email or password.');const user={id:u.id,name:u.name,email:u.email,role:u.role};res.json({success:true,user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})});});
app.post('/api/startup-planner/analyze',[body('capital').isInt({min:200000,max:10000000})],(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Capital must be a whole PKR amount between 200,000 and 10,000,000.');const capital=Number(req.body.capital);res.json({success:true,capital,notice:'All figures are planning estimates. Actual costs vary by city, suppliers, rent, staffing and business model.',options:recommend(capital,req.body)});});
app.get('/api/business-templates/:id',(req,res)=>{const t=db.prepare('SELECT * FROM business_templates WHERE id=?').get(req.params.id);if(!t)return fail(res,404,'Business template not found.');res.json({success:true,template:{...t,cost_breakdown:fields(t)}});});
app.post('/api/startup-plans',auth,[body('capital').isInt({min:200000,max:10000000}),body('template_id').isInt()],(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Valid capital and business option are required.');const t=db.prepare('SELECT * FROM business_templates WHERE id=?').get(req.body.template_id);if(!t)return fail(res,404,'Business template not found.');const q=db.prepare('INSERT INTO startup_plans(user_id,template_id,business_name,capital,category,location,experience,risk_preference,estimated_setup_cost,estimated_equipment_cost,estimated_inventory_cost,estimated_marketing_cost,estimated_working_capital,emergency_reserve,estimated_monthly_expenses) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');const r=q.run(req.user.id,t.id,t.name,req.body.capital,t.category,req.body.city||'',req.body.experience||'',req.body.risk_preference||'',t.setup_cost+t.rent_deposit,t.equipment_cost,t.inventory_cost,t.marketing_cost,t.working_capital,t.emergency_reserve,t.estimated_monthly_expenses);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Startup plan saved.'});});
app.get('/api/startup-plans',auth,(req,res)=>res.json({success:true,plans:db.prepare('SELECT * FROM startup_plans WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
app.post('/api/businesses/from-plan/:id',auth,(req,res)=>{const p=db.prepare('SELECT * FROM startup_plans WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!p)return fail(res,404,'Startup plan not found.');const r=db.prepare('INSERT INTO businesses(user_id,name,category,city,startup_capital,status) VALUES(?,?,?,?,?,?)').run(req.user.id,p.business_name,p.category,p.location,p.capital,'Planning');res.status(201).json({success:true,id:r.lastInsertRowid,message:'Business created from your plan.'});});
app.get('/api/businesses',auth,(req,res)=>res.json({success:true,businesses:db.prepare('SELECT * FROM businesses WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
app.get('/api/dashboard/:businessId',auth,(req,res)=>{const b=db.prepare('SELECT * FROM businesses WHERE id=? AND user_id=?').get(req.params.businessId,req.user.id);if(!b)return fail(res,404,'Business not found.');const one=(sql)=>db.prepare(sql).get(b.id);res.json({success:true,business:b,metrics:{sales:one('SELECT COALESCE(SUM(total),0) v FROM sales WHERE business_id=?').v,expenses:one('SELECT COALESCE(SUM(amount),0) v FROM expenses WHERE business_id=?').v,customers:one('SELECT COUNT(*) v FROM customers WHERE business_id=?').v,products:one('SELECT COUNT(*) v FROM products WHERE business_id=?').v,low_stock:one('SELECT COUNT(*) v FROM products WHERE business_id=? AND stock<=minimum_stock').v}});});
app.use((err,req,res,next)=>{console.error(err);fail(res,500,'Something went wrong.');});
app.listen(PORT,()=>console.log(`BusinessPro running at http://localhost:${PORT}`));
