require('dotenv').config();
require('./database/init');
const express=require('express'), cors=require('cors'), bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken');
const {body, validationResult}=require('express-validator');
const db=require('./database/db');
const app=express(), PORT=process.env.PORT||5000, SECRET=process.env.JWT_SECRET||'development-only-secret';
app.use(cors()); app.use(express.json()); app.use(express.static('public'));
const fail=(res,status,message)=>res.status(status).json({success:false,message});
const audit=(userId,action,entity,entityId,details='')=>db.prepare('INSERT INTO audit_logs(user_id,action,entity,entity_id,details) VALUES(?,?,?,?,?)').run(userId||null,action,entity,entityId||null,details);
function auth(req,res,next){ const token=(req.headers.authorization||'').replace('Bearer ',''); try{req.user=jwt.verify(token,SECRET);next();}catch{return fail(res,401,'Please log in to continue.');} }
function ownedBusiness(req,res){const business=db.prepare('SELECT * FROM businesses WHERE id=? AND user_id=?').get(Number(req.params.businessId),req.user.id);if(!business){fail(res,404,'Business not found or you do not have access.');return null;}return business;}
function fields(template){return {setup_cost:template.setup_cost,rent_deposit:template.rent_deposit,equipment_cost:template.equipment_cost,inventory_cost:template.inventory_cost,staff_cost:template.staff_cost,marketing_cost:template.marketing_cost,technology_cost:template.technology_cost,emergency_reserve:template.emergency_reserve,working_capital:template.working_capital};}
function recommend(capital, filters={}) { let rows=db.prepare('SELECT * FROM business_templates').all(); if(filters.category&&filters.category!=='Any') rows=rows.filter(r=>r.category===filters.category); if(filters.online==='Yes') rows=rows.filter(r=>r.online_supported); if(filters.physical==='Yes') rows=rows.filter(r=>r.physical_supported); return rows.map(t=>{const gap=t.recommended_capital-capital; let status= gap<=0 && capital>=t.recommended_capital*1.35 ? 'Large Reserve Available' : gap<=0 ? 'Within Estimated Budget' : capital>=t.minimum_capital*0.9 ? 'Near Budget — review lean allocation' : 'Requires Additional Capital'; const score=Math.max(0,100-Math.abs(gap)/Math.max(capital,1)*65)+(capital>=t.minimum_capital?15:0); return {...t,budget_status:status,fit_score:Math.round(score),capital_difference:gap,cost_breakdown:fields(t),why_fit: status==='Within Estimated Budget'?'Its recommended planning capital fits your entered amount.':status==='Large Reserve Available'?'Your amount supports the model and leaves room for a larger launch or reserve.':status==='Near Budget — review lean allocation'?'A lean version may be possible; validate costs and retain emergency cash.':'Its standard planning requirement is above your entered capital.'};}).sort((a,b)=>b.fit_score-a.fit_score); }
app.post('/api/auth/register',[body('name').trim().notEmpty(),body('email').isEmail(),body('password').isLength({min:8})],async(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Name, valid email and an 8-character password are required.');const {name,email,password}=req.body;if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return fail(res,409,'Email already registered.');const info=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email,bcrypt.hashSync(password,10));const user={id:info.lastInsertRowid,name,email,role:'owner'};audit(user.id,'ACCOUNT_CREATED','user',user.id,`Account created: ${email}`);res.status(201).json({success:true,user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})});});
app.post('/api/auth/login',async(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password||'',u.password_hash)){audit(null,'LOGIN_FAILED','auth',null,`Failed login for: ${String(req.body.email||'').slice(0,160)}`);return fail(res,401,'Invalid email or password.');}const user={id:u.id,name:u.name,email:u.email,role:u.role};audit(u.id,'LOGIN','auth',u.id,`Successful login: ${u.email}`);res.json({success:true,user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})});});
app.post('/api/auth/logout',auth,(req,res)=>{audit(req.user.id,'LOGOUT','auth',req.user.id,`Logout: ${req.user.email}`);res.json({success:true,message:'Logout recorded.'});});
app.get('/api/audit-logs',auth,(req,res)=>{if(req.user.role!=='admin')return fail(res,403,'Administrator access is required.');const logs=db.prepare('SELECT audit_logs.*, users.name, users.email FROM audit_logs LEFT JOIN users ON users.id=audit_logs.user_id ORDER BY audit_logs.created_at DESC, audit_logs.id DESC LIMIT 200').all();res.json({success:true,logs});});
app.post('/api/startup-planner/analyze',[body('capital').isInt({min:200000,max:10000000})],(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Capital must be a whole PKR amount between 200,000 and 10,000,000.');const capital=Number(req.body.capital);res.json({success:true,capital,notice:'All figures are planning estimates. Actual costs vary by city, suppliers, rent, staffing and business model.',options:recommend(capital,req.body)});});
app.get('/api/business-templates/:id',(req,res)=>{const t=db.prepare('SELECT * FROM business_templates WHERE id=?').get(req.params.id);if(!t)return fail(res,404,'Business template not found.');res.json({success:true,template:{...t,cost_breakdown:fields(t)}});});
app.post('/api/startup-plans',auth,[body('capital').isInt({min:200000,max:10000000}),body('template_id').isInt()],(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Valid capital and business option are required.');const t=db.prepare('SELECT * FROM business_templates WHERE id=?').get(req.body.template_id);if(!t)return fail(res,404,'Business template not found.');const q=db.prepare('INSERT INTO startup_plans(user_id,template_id,business_name,capital,category,location,experience,risk_preference,estimated_setup_cost,estimated_equipment_cost,estimated_inventory_cost,estimated_marketing_cost,estimated_working_capital,emergency_reserve,estimated_monthly_expenses) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');const r=q.run(req.user.id,t.id,t.name,req.body.capital,t.category,req.body.city||'',req.body.experience||'',req.body.risk_preference||'',t.setup_cost+t.rent_deposit,t.equipment_cost,t.inventory_cost,t.marketing_cost,t.working_capital,t.emergency_reserve,t.estimated_monthly_expenses);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Startup plan saved.'});});
app.get('/api/startup-plans',auth,(req,res)=>res.json({success:true,plans:db.prepare('SELECT * FROM startup_plans WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
app.post('/api/businesses/from-plan/:id',auth,(req,res)=>{const p=db.prepare('SELECT * FROM startup_plans WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!p)return fail(res,404,'Startup plan not found.');const r=db.prepare('INSERT INTO businesses(user_id,name,category,city,startup_capital,status) VALUES(?,?,?,?,?,?)').run(req.user.id,p.business_name,p.category,p.location,p.capital,'Planning');res.status(201).json({success:true,id:r.lastInsertRowid,message:'Business created from your plan.'});});
app.get('/api/businesses',auth,(req,res)=>res.json({success:true,businesses:db.prepare('SELECT * FROM businesses WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
app.post('/api/businesses',auth,[body('name').trim().notEmpty(),body('startup_capital').optional().isInt({min:0,max:10000000})],(req,res)=>{if(!validationResult(req).isEmpty())return fail(res,422,'Business name and a valid capital amount are required.');const r=db.prepare('INSERT INTO businesses(user_id,name,category,city,startup_capital,status) VALUES(?,?,?,?,?,?)').run(req.user.id,req.body.name,req.body.category||'Other',req.body.city||'',Number(req.body.startup_capital||0),req.body.status||'Active');audit(req.user.id,'BUSINESS_CREATED','business',r.lastInsertRowid,`Created business: ${req.body.name}`);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Business created.'});});
app.get('/api/businesses/:businessId/business-plan',auth,(req,res)=>{const business=ownedBusiness(req,res);if(!business)return;const templates=db.prepare('SELECT * FROM business_templates WHERE category=?').all(business.category);const all=templates.length?templates:db.prepare('SELECT * FROM business_templates').all();const capital=Number(business.startup_capital||0);const t=all.sort((a,b)=>Math.abs(a.recommended_capital-capital)-Math.abs(b.recommended_capital-capital))[0];const budgetStatus=capital>=t.recommended_capital?'Your capital supports the standard launch assumptions.':'Use a lean first phase, negotiate suppliers, and protect a cash reserve.';const plan={business,reference_template:t,generated_at:new Date().toISOString(),disclaimer:'This is a planning guide generated from example business assumptions. Validate city-specific costs, licences, suppliers and demand before investing.',sections:[['Business overview',`${business.name} is a ${business.category} business planned for ${business.city||'your selected city'}. The operating model is informed by the ${t.name} template.`],['Capital strategy',`Available capital: PKR ${capital.toLocaleString('en-PK')}. ${budgetStatus} Prioritise setup, equipment/inventory, working capital and an emergency reserve.`],['Target customers',business.category==='Food'?'Nearby residents, office workers, students and delivery customers.':'Local customers, repeat buyers, referrals and relevant online audiences.'],['First 30 days','Week 1: validate demand, competitors, pricing, registration and location. Week 2: confirm suppliers, equipment, branding and payments. Week 3: set inventory/services, social profiles and staff training. Week 4: soft launch, collect feedback and track every sale.'],['Sales and marketing',`Set an opening offer, use WhatsApp Business and Google Maps, request customer reviews, and allocate approximately PKR ${t.marketing_cost.toLocaleString('en-PK')} as an initial marketing assumption.`],['Operations',`Track every sale and expense in BusinessPro. Review low stock daily. Expected example monthly operating cost: PKR ${t.estimated_monthly_expenses.toLocaleString('en-PK')}.`],['Risks and controls',`Risk level: ${t.risk_level}. Keep the example emergency reserve of PKR ${t.emergency_reserve.toLocaleString('en-PK')}, avoid over-ordering stock, and review cash weekly.`],['Growth roadmap',`After consistent sales, expand the best-selling range, add online ordering where suitable, and reinvest only after working capital remains protected. ${t.scalability} scalability assumption.`]]};audit(req.user.id,'BUSINESS_PLAN_GENERATED','business',business.id,`Generated plan for: ${business.name}`);res.json({success:true,plan});});
app.get('/api/businesses/:businessId/products',auth,(req,res)=>{if(!ownedBusiness(req,res))return;res.json({success:true,products:db.prepare('SELECT * FROM products WHERE business_id=? ORDER BY created_at DESC').all(req.params.businessId)});});
app.post('/api/businesses/:businessId/products',auth,[body('name').trim().notEmpty(),body('sale_price').isFloat({min:0}),body('stock').isFloat({min:0})],(req,res)=>{const business=ownedBusiness(req,res);if(!business)return;if(!validationResult(req).isEmpty())return fail(res,422,'Product name, selling price and stock are required.');const r=db.prepare('INSERT INTO products(business_id,sku,name,purchase_price,sale_price,stock,minimum_stock) VALUES(?,?,?,?,?,?,?)').run(business.id,req.body.sku||'',req.body.name,Number(req.body.purchase_price||0),Number(req.body.sale_price),Number(req.body.stock),Number(req.body.minimum_stock||0));audit(req.user.id,'PRODUCT_CREATED','product',r.lastInsertRowid,`Added product: ${req.body.name}`);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Product added.'});});
app.get('/api/businesses/:businessId/customers',auth,(req,res)=>{if(!ownedBusiness(req,res))return;res.json({success:true,customers:db.prepare('SELECT * FROM customers WHERE business_id=? ORDER BY created_at DESC').all(req.params.businessId)});});
app.post('/api/businesses/:businessId/customers',auth,[body('name').trim().notEmpty()],(req,res)=>{const business=ownedBusiness(req,res);if(!business)return;if(!validationResult(req).isEmpty())return fail(res,422,'Customer name is required.');const r=db.prepare('INSERT INTO customers(business_id,name,phone,email,customer_type) VALUES(?,?,?,?,?)').run(business.id,req.body.name,req.body.phone||'',req.body.email||'',req.body.customer_type||'Individual');audit(req.user.id,'CUSTOMER_CREATED','customer',r.lastInsertRowid,`Added customer: ${req.body.name}`);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Customer added.'});});
app.get('/api/businesses/:businessId/expenses',auth,(req,res)=>{if(!ownedBusiness(req,res))return;res.json({success:true,expenses:db.prepare('SELECT * FROM expenses WHERE business_id=? ORDER BY expense_date DESC,id DESC').all(req.params.businessId)});});
app.post('/api/businesses/:businessId/expenses',auth,[body('category').trim().notEmpty(),body('amount').isFloat({gt:0})],(req,res)=>{const business=ownedBusiness(req,res);if(!business)return;if(!validationResult(req).isEmpty())return fail(res,422,'Expense category and a positive amount are required.');const r=db.prepare('INSERT INTO expenses(business_id,category,description,amount,expense_date) VALUES(?,?,?,?,?)').run(business.id,req.body.category,req.body.description||'',Number(req.body.amount),req.body.expense_date||new Date().toISOString().slice(0,10));audit(req.user.id,'EXPENSE_CREATED','expense',r.lastInsertRowid,`Added ${req.body.category} expense: PKR ${req.body.amount}`);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Expense added.'});});
app.get('/api/businesses/:businessId/sales',auth,(req,res)=>{if(!ownedBusiness(req,res))return;res.json({success:true,sales:db.prepare('SELECT sales.*, customers.name customer_name FROM sales LEFT JOIN customers ON customers.id=sales.customer_id WHERE sales.business_id=? ORDER BY sales.sale_date DESC,id DESC').all(req.params.businessId)});});
app.post('/api/businesses/:businessId/sales',auth,[body('total').isFloat({gt:0})],(req,res)=>{const business=ownedBusiness(req,res);if(!business)return;if(!validationResult(req).isEmpty())return fail(res,422,'Sale total must be greater than zero.');const r=db.prepare('INSERT INTO sales(business_id,customer_id,total,sale_date) VALUES(?,?,?,?)').run(business.id,req.body.customer_id||null,Number(req.body.total),new Date().toISOString());audit(req.user.id,'SALE_CREATED','sale',r.lastInsertRowid,`Created sale: PKR ${req.body.total}`);res.status(201).json({success:true,id:r.lastInsertRowid,message:'Sale recorded.'});});
app.get('/api/dashboard/:businessId',auth,(req,res)=>{const b=db.prepare('SELECT * FROM businesses WHERE id=? AND user_id=?').get(req.params.businessId,req.user.id);if(!b)return fail(res,404,'Business not found.');const one=(sql)=>db.prepare(sql).get(b.id);res.json({success:true,business:b,metrics:{sales:one('SELECT COALESCE(SUM(total),0) v FROM sales WHERE business_id=?').v,expenses:one('SELECT COALESCE(SUM(amount),0) v FROM expenses WHERE business_id=?').v,customers:one('SELECT COUNT(*) v FROM customers WHERE business_id=?').v,products:one('SELECT COUNT(*) v FROM products WHERE business_id=?').v,low_stock:one('SELECT COUNT(*) v FROM products WHERE business_id=? AND stock<=minimum_stock').v}});});
app.use((err,req,res,next)=>{console.error(err);fail(res,500,'Something went wrong.');});
app.listen(PORT,()=>console.log(`BusinessPro running at http://localhost:${PORT}`));
