const db = require('./db');
db.exec(`
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS businesses (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, name TEXT NOT NULL, category TEXT, city TEXT, startup_capital INTEGER, status TEXT DEFAULT 'Planning', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS business_templates (id INTEGER PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, description TEXT, minimum_capital INTEGER NOT NULL, recommended_capital INTEGER NOT NULL, maximum_capital INTEGER NOT NULL, equipment_cost INTEGER DEFAULT 0, inventory_cost INTEGER DEFAULT 0, setup_cost INTEGER DEFAULT 0, rent_deposit INTEGER DEFAULT 0, staff_cost INTEGER DEFAULT 0, marketing_cost INTEGER DEFAULT 0, technology_cost INTEGER DEFAULT 0, emergency_reserve INTEGER DEFAULT 0, working_capital INTEGER DEFAULT 0, estimated_monthly_expenses INTEGER DEFAULT 0, estimated_revenue_low INTEGER DEFAULT 0, estimated_revenue_high INTEGER DEFAULT 0, break_even_months INTEGER, risk_level TEXT, scalability TEXT, online_supported INTEGER DEFAULT 0, physical_supported INTEGER DEFAULT 1, experience_required TEXT DEFAULT 'Beginner', created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS startup_plans (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL, template_id INTEGER, business_name TEXT, capital INTEGER NOT NULL CHECK(capital >= 200000 AND capital <= 10000000), category TEXT, location TEXT, experience TEXT, risk_preference TEXT, estimated_setup_cost INTEGER, estimated_equipment_cost INTEGER, estimated_inventory_cost INTEGER, estimated_marketing_cost INTEGER, estimated_working_capital INTEGER, emergency_reserve INTEGER, estimated_monthly_expenses INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(template_id) REFERENCES business_templates(id));
CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, name TEXT NOT NULL, phone TEXT, email TEXT, customer_type TEXT DEFAULT 'Individual', created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, sku TEXT, name TEXT NOT NULL, purchase_price REAL DEFAULT 0, sale_price REAL DEFAULT 0, stock REAL DEFAULT 0, minimum_stock REAL DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS expenses (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, category TEXT NOT NULL, description TEXT, amount REAL NOT NULL, expense_date TEXT NOT NULL, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS sales (id INTEGER PRIMARY KEY, business_id INTEGER NOT NULL, customer_id INTEGER, total REAL NOT NULL, sale_date TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(business_id) REFERENCES businesses(id));
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY, user_id INTEGER, action TEXT NOT NULL, entity TEXT NOT NULL, entity_id INTEGER, details TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
`);
